solution: CyLR.sln
matrix:
  include:
    - os: windows
      language: csharp
      mono: none
      dotnet: none

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install dotnetcore-sdk 7zip ; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then PowerShell -Command 'Set-ExecutionPolicy -ExecutionPolicy RemoteSigned' ; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then PowerShell -File scripts/test_win.ps1 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then PowerShell -File scripts/build_win.ps1 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then PowerShell -File scripts/package_win.ps1 ; fi

deploy:
  provider: releases
  api_key:
    secure: YzyMuKGdZSEMfFFhxQKbYWck/0rhF8JqwBQX5QYzNTKC0JRJKhaZPAf9Wbyc+5AgRqv2vr2hwPvSC6BwWSkDGLwzNe89KFjKKJB+AD/09gsChC6FfLaYMMGjOcmSyHtD6vEXJBovLeCE4ecPqjLZH/jhhU5+LyvAUOC7cgPXNhLNgzv5rRgdI1MvB6KS4kAhp5FIfZ4UIC9izTFJwXoiT8b5nE6kxY5HkiwpK+qfyXaKhdow9/lqBkU3nblyP85yCCxjAQWVcR6BUGEImDvjYjx5TlP1SHN7R1bkK0IqOK1DnNPzrYpVd/ejHGHGY3vy8+qAw9UyaDqosmH220qZ13gV7AMd/UnI6SkKCX08TfUeQx1dgrMBC1weluBI223kjwPPJjsC/6TO4Xyu1QYHns2R+M4C25htNNio5mLbrU4FnMtO2uxZCyEHz6UxbXYrsKRV/szLxfi9B42p/pQ6jIqEyo22HKsGlQqGYZuVqRb1S32h2dLgFzPeawScGJrgoJxK7EkjKyvqgxGrCJAU8357I0WqDf6RTsLeCQF8pqrDl7GLDCftn7ULBSXNjSUmIjZEZw7UShM3ZhQaIeYzNqgyK1kRApTEKJHy3itmDx47nfyGfXb6CAfnoaqKyattB8hsxKQh1cea+z8duxp7UxbAVBIABRcKsizl5YViQRE=
  file_glob: true
  file: archive/**/*
  name: Draft Release
  draft: true
  skip_cleanup: true
