solution: CyLR.sln
matrix:
  include:
    - os: windows
      language: csharp
      mono: none
      dotnet: none

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install dotnetcore-sdk 7zip ; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then PowerShell -Command 'Set-ExecutionPolicy -ExecutionPolicy RemoteSigned' ; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then PowerShell -File scripts/test_win.ps1 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then PowerShell -File scripts/build_win.ps1 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then PowerShell -File scripts/package_win.ps1 ; fi

deploy:
  provider: releases
  api_key:
    secure: SmtdvBXUw7LRYibQCBI+MgTu86kXuMYjH1A2NgbGJU8kX+AsqU2T9q9Ct6ozx7QT4o92VAkbT9xpzUEJw7uSWfcx16WRFPVCYNVKzuA/9FJH0pbHNtAnVd2h5LwFYmoWVM2p7KQT5oiR9BpSP/e8stshLt+ndJE5r4MaKJ01I4mGyZa25FMmEB6Ee7O4XhZUNRIsJijwBfd/+JppOcSaMIva0SxUFcCNsa1eJ5N5f4MzOloSyLhv6MG1gYke0FMne8Kd4aPWn+8QD8y/XlP22f3flNv9t4Fl16U0SfYRVy7MwfzuFi3kSa0ojZmSJdeU8pHTkDWI2Pv5PJAIaPxEsAHN1rwoz3T3teeuUKxq4ZUUS/FfcyfwZOlmK6KoEK8TOwtGZPAqEiOHzvzSQu45sKxy09NvbCNG4Ang/5dZSnzQVst4dHaq1shVqEeo9I8//ldnPnyLt72zZ0fXGiIAc6fzFedPVGbbKxXU9Rss5ND7OOhZbSrRIhBmTYHKIeR+KEkNjQZjFeKeoT6A/y3wISlHl552VO67Lw+r7XVzflf7Z5S9ALJ9D9eNWkkiGN7rOFKgAzruXlVDzYqKn8PA+NOHi9ajsXFuKl5DHoIN54zulYwzXmyH/ht6l5jsu29ST+h2uAYuh1SOZAgBugzFY1OIkPbC9nUUxQ0E8okvlxs=
  file_glob: true
  file: archive/**/*
  name: Draft Release
  draft: true
  skip_cleanup: true
  overwrite: true
